apiVersion: v1
kind: Service
metadata:
    name: "docapp"
    labels:
        app: "docapp"
spec:
    type: LoadBalancer
    ports:
    - port: 5002
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "docapp"