apiVersion: v1
kind: Service
metadata:
    name: "kubecluster"
    labels:
        app: "kubecluster"
spec:
    type: LoadBalancer
    ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
    selector:
        app: "kubecluster"
