apiVersion: v1
kind: Service
metadata:
    name: "kubecluster"
    labels:
        app: "kubecluster"
spec:
    type: LoadBalancer
    ports:
    - port: 31677
      targetPort: 5002
      nodePort: 0
      protocol: TCP
      name: default
    selector:
        app: "kubecluster"
