on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: docappapi.azurecr.io
        username: ${{ secrets.acr_docappapi_username }}
        password: ${{ secrets.acr_docappapi_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t docappapi.azurecr.io/docappt:${{ github.sha }}
        docker push docappapi.azurecr.io/docappt:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_docappt_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep docappt3575 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace docappt3575`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: docappt3575
        container-registry-url: docappapi.azurecr.io
        container-registry-username: ${{ secrets.acr_docappapi_username }}
        container-registry-password: ${{ secrets.acr_docappapi_password }}
        secret-name: docapptdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: docappt3575
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          docappapi.azurecr.io/docappt:${{ github.sha }}
        imagepullsecrets: |
          docapptdockerauth